import time
import math
import random
import os
import msvcrt

#Gemaakt door Jurre
#Copyright reserved
#versie 0.1

#Het idee is dat elk wapen een level heeft en dat de levels stijgen doormiddel van hitpoints.

#Hitpoints en wapens
ratio1 = [5, 6, 7, 7, 8] #Machine Gun
ratio2 = [2, 3, 3, 4, 5] #Pistool
ratio3 = [5, 6, 7, 7, 8] #Granaat
ratio4 = [6, 7, 8, 9, 10]#Vuurbal
ratio5 = [4, 4, 5, 5, 5] #Levens
ratio6 = [3, 4, 5, 6, 7] #Motor
ratio7 = [3, 3, 4, 5, 6] #Bom

#wapens = ["teleportatie", "motor", "bom", "medkit"]
wapens = ["motor", "bom"]

#personages:
namen = ["Steve Jobs", "Gekke Henkie", "Maiseter", "Ayachi master", "Jason Voorhees", "Jelle", "Abbe", "Rembrandt", "Jezus", "Kapitein", "Cobra", "Automobilist", "Gert-Jan meijer", "Golfballetje", "Pixel", "Pacboi", "LongBoi", "Calvijn", "Roodbaard", "Het ij", "Zakje", "Teletubbie", "De huismus", "Koning-Rat", "Midas", "Programmeur", "Student", "Feracci", "Uw rechter", "De duivel", "Demon", "De boer", "Subject-3419", "D-9341", "NXT-BOT", "Killer", "Kabouter", "Je docent", "Hyperboy", "Varg", "John", "Het object", "ROBOT", "cryclone dt3", "Codemaker_4", "psyclone", "De alchemist", "Proctoloog", "Motje", "Shitbag", "Hakan-bot", "Jurjen-bot", "Harvey", "Bob", "Ahmed", "Commandant", "De generaal", "Scout", "Sergeant", "De chirurg", "Paddenstoel", "De paus", "De excorcist", "Jochem", "R4KE", "Bamibal", "De doctor", "Sub-Zero", "Scorpion", "Sinterklas", "Knuffelbeer", "De Hertog", "Chris Hadfield", "Vsauce", "Einstein", "Piloot", "Zeus", "Spion", "De aap", "Terminator", "SWAT", "Deo", "De ninja", "RiddimLord", "Yuki", "Een bouwvakker", "Filips II", "De koning", "Slenderman", "SCP-173", "Windows", "User", "Stekkerdoos", "Admin", "Haarsma", "Obama", "Boef", "Militair", "Noob", "Wacho", "Orang", "Karel V", "Luther", "Issam", "Codecracker", "De Blox", "De vijand", "Pewdiepie", "Markiplier", "Zwarte ruiter", "Obunga", "Koning Arthur", "Stickman", "God", "INFEKT", "Trump", "Hakan", "Jurjen", "Bloxyboy", "Jurre", "Mr. Plak", "Amin", "Strijder", "De profeet", "Mohammed", "Kirito", "Otto", "Guerillastrijder", "je moeder"]

#timers en hp meters
slaap = [0.5, 0.6, 0.7, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8, 3]
spin = 0.005

hp1 = 100 #HP jou
hp2 = 100 #HP vijand

while True:
    for i in range(1):
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("________________________________")
        time.sleep(0.5)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("___/ \__________________________")
        time.sleep(0.05)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("   /|\                          ")
        print("___/ \__________________________")
        time.sleep(0.05)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("    @                           ")
        print("   /|\                          ")
        print("___/ \__________________________")
        time.sleep(0.1)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("    @                           ")
        print("   /|\                          ")
        print("___/ \____________________/ \___")
        time.sleep(0.05)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("    @                           ")
        print("   /|\                    /|\   ")
        print("___/ \____________________/ \___")
        time.sleep(0.05)
        os.system('cls')
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("                                ")
        print("    @                      @    ")
        print("   /|\                    /|\   ")
        print("___/ \____________________/ \___")
  
    time.sleep(1)
    print("")
    print("")
    print("")
    print("Geef uw karakter een naam.")
    print("")
    naam = input(": ")
    os.system('cls')
    print("                                ")
    print("  " + naam)
    print("  " + str(hp1) + "hp")
    print("                                ")
    print("                                ")
    print("                                ")
    print("    @                      @    ")
    print("   /|\                    /|\   ")
    print("___/ \____________________/ \___")
    time.sleep(1)
    for i in range(40):
        spin = spin + 0.006
        os.system('cls')
        naam2 = random.choice(namen)
        print("                                ")
        print("  " + naam)
        print("  " + str(hp1) + "hp")
        print("                         " + naam2)
        print("                         " + str(hp2) + "hp")
        print("                                ")
        print("    @                      @    ")
        print("   /|\                    /|\   ")
        print("___/ \____________________/ \___")
        print("")
        print("")
        print("")
        print("U speelt tegen " + naam2 + ".")
        time.sleep(spin)
    for i in range(4):
        os.system('cls')
        print("                                ")
        print("  " + naam)
        print("  " + str(hp1) + "hp")
        print("                         " + naam2)
        print("                         " + str(hp2) + "hp")
        print("                                ")
        print("   _@_                    \@/   ")
        print("    |                      |    ")
        print("___/ \____________________/ \___")
        print("")
        print("")
        print("")
        print("U speelt tegen " + naam2 + ".")
        time.sleep(0.5)
        os.system('cls')
        print("                                ")
        print("  " + naam)
        print("  " + str(hp1) + "hp")
        print("                         " + naam2)
        print("                         " + str(hp2) + "hp")
        print("                                ")
        print("   \@/                    _@_   ")
        print("    |                      |    ")
        print("___/ \____________________/ \___")
        print("")
        print("")
        print("")
        print("U speelt tegen " + naam2 + ".")
        time.sleep(0.5)
    print("")
    print("")
    print("Klik op enter om te beginnen.")

    begin = input("")
    if begin == "":
        print("")
        time.sleep(0.5)
        
    while True:
        r6 = random.choice(ratio6)
        r7 = random.choice(ratio7)
        
        lengte = random.choice(slaap)
        wapen = random.choice(wapens)
        os.system('cls')
        print("                                ")
        print("  " + naam)
        print("  " + str(hp1) + "hp")
        print("                         " + naam2)
        print("                         " + str(hp2) + "hp")
        print("                                ")
        print("    @                      @    ")
        print("   /|\                    /|\   ")
        print("___/ \____________________/ \___")
        time.sleep(1)
        print("")
        print("")
        print("")
        print(naam2 + " is aan de beurt.")
        time.sleep(lengte)
        print("")
        print("")
        print(naam2 + " gebruikt zijn " + wapen + ".")
        time.sleep(2)

        if wapen == "bom":
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                      @    ")
            print("   /|\                    /|\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                     _@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                    ╥_@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    @                     \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(2)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("    o                    " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    @                     \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("    |                    " + naam2)
            print("    o                    " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    @                     \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("    |                    " + str(hp2) + "hp")
            print("    o                    ╥      ")
            print("    @                     \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("    |                    ╥      ")
            print("    #*                    \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            hp1 -= int(r7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    #*                    \@    ")
            print("   *|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            hp1 -= int(r7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("   *|*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            hp1 -= int(r7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("   *#*                     |\   ")
            print("___/ *____________________/ \___")
            time.sleep(0.1)
            hp1 -= int(r7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("  **#*                     |\   ")
            print("___* *____________________/ \___")
            time.sleep(0.1)
            hp1 -= int(r7)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("  **#*                     |\   ")
            print("___/ *____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("  **#*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("  */#*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("   ##*                    \@    ")
            print("   /#*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    #*                    \@    ")
            print("   /#*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    #*                    \@    ")
            print("   /|*                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    #*                    \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    @*                    \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                         ╥      ")
            print("    @                     \@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.5)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                    ╥_@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.5)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                     _@    ")
            print("   /|\                     |\   ")
            print("___/ \____________________/ \___")
            time.sleep(0.3)
            
        if wapen == "motor":
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                         " + naam2)
            print("                         " + str(hp2) + "hp")
            print("                                ")
            print("    @                  @__,     ")
            print("   /|\                 ,>_/-_   ")
            print("___/ \________________(*)`\(*)__")
            time.sleep(1)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                        " + naam2)
            print("                        " + str(hp2) + "hp")
            print("                                ")
            print("    @                 @__,      ")
            print("   /|\                ,>_/-_    ")
            print("___/ \_______________(*)`\(*)___")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                       " + naam2)
            print("                       " + str(hp2) + "hp")
            print("                                ")
            print("    @_               @__,       ")
            print("   /|                ,>_/-_     ")
            print("___/ \______________(*)`\(*)____")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                      " + naam2)
            print("                      " + str(hp2) + "hp")
            print("                                ")
            print("    @_              @__,        ")
            print("   /|               ,>_/-_      ")
            print("___/ \_____________(*)`\(*)_____")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                     " + naam2)
            print("                     " + str(hp2) + "hp")
            print("                                ")
            print("    @_             @__,         ")
            print("   /|              ,>_/-_       ")
            print("___/ \____________(*)`\(*)______")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                    " + naam2)
            print("                    " + str(hp2) + "hp")
            print("                                ")
            print("    @_            @__,          ")
            print("   /|             ,>_/-_        ")
            print("___/ \___________(*)`\(*)_______")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                   " + naam2)
            print("                   " + str(hp2) + "hp")
            print("                                ")
            print("    @_           @__,           ")
            print("   /|            ,>_/-_         ")
            print("___/ \__________(*)`\(*)________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                  " + naam2)
            print("                  " + str(hp2) + "hp")
            print("                                ")
            print("    @_          @__,            ")
            print("   /|           ,>_/-_          ")
            print("___/ \_________(*)`\(*)_________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                 " + naam2)
            print("                 " + str(hp2) + "hp")
            print("                                ")
            print("    @_         @__,             ")
            print("   /|          ,>_/-_           ")
            print("___/ \________(*)`\(*)__________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("                " + naam2)
            print("                " + str(hp2) + "hp")
            print("                                ")
            print("    @_        @__,              ")
            print("   /|         ,>_/-_            ")
            print("___/ \_______(*)`\(*)___________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("               " + naam2)
            print("               " + str(hp2) + "hp")
            print("                                ")
            print("    @_       @__,               ")
            print("   /|        ,>_/-_             ")
            print("___/ \______(*)`\(*)____________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("              " + naam2)
            print("              " + str(hp2) + "hp")
            print("                                ")
            print("    @_      @__,                ")
            print("   /|       ,>_/-_              ")
            print("___/ \_____(*)`\(*)_____________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("             " + naam2)
            print("             " + str(hp2) + "hp")
            print("                                ")
            print("    @_     @__,                 ")
            print("   /|      ,>_/-_               ")
            print("___/ \____(*)`\(*)______________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("            " + naam2)
            print("            " + str(hp2) + "hp")
            print("                                ")
            print("    @_    @__,                  ")
            print("   /|     ,>_/-_                ")
            print("___/ \___(*)`\(*)_______________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("           " + naam2)
            print("           " + str(hp2) + "hp")
            print("                                ")
            print("    @_   @__,                   ")
            print("   /|    ,>_/-_                 ")
            print("___/ \__(*)`\(*)________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("          " + naam2)
            print("          " + str(hp2) + "hp")
            print("                                ")
            print("    @|  @__,                    ")
            print("   /|   ,>_/-_                  ")
            print("___/ \_(*)`\(*)_________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("         " + naam2)
            print("         " + str(hp2) + "hp")
            print("                                ")
            print("    @| @__,                     ")
            print("   /|  ,>_/-_                   ")
            print("___/ \(*)`\(*)__________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("        " + naam2)
            print("        " + str(hp2) + "hp")
            print("                                ")
            print("   \@|@__,                      ")
            print("    | ,>_/-_                    ")
            print("___/ (*)`\(*)___________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("       " + naam2)
            print("       " + str(hp2) + "hp")
            print("                                ")
            print("  \@@__,                        ")
            print("    |,>_/-_                     ")
            print("___#(*)`\(*)____________________")
            time.sleep(0.02)
            hp1 -= int(r6)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("      " + naam2)
            print("      " + str(hp2) + "hp")
            print("                                ")
            print("  #@__,                         ")
            print(" # ,>_/-_                       ")
            print("__(*)`\(*)______________________")
            time.sleep(0.02)
            hp1 -= int(r6)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("     " + naam2)
            print("     " + str(hp2) + "hp")
            print("                                ")
            print("  @__,                          ")
            print("  ,>_/-_                        ")
            print("_(*)`\(*)_______________________")
            time.sleep(0.02)
            hp1 -= int(r6)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("    " + naam2)
            print("    " + str(hp2) + "hp")
            print("                                ")
            print(" @__,                           ")
            print(" ,>_/-_                         ")
            print("(*)`\(*)________________________")
            time.sleep(0.02)
            hp1 -= int(r6)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("   " + naam2)
            print("   " + str(hp2) + "hp")
            print("                                ")
            print("@__,                            ")
            print(",>_/-_                          ")
            print("*)`\(*)_________________________")
            time.sleep(0.02)
            hp1 -= int(r6)
            if hp2 < 1:
                hp2 = 0
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("  " + naam2)
            print("  " + str(hp2) + "hp")
            print("                                ")
            print("__,                             ")
            print(">_/-_                           ")
            print(")`\(*)__________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print(" " + naam2)
            print(" " + str(hp2) + "hp")
            print("                                ")
            print("_,                              ")
            print("_/-_                            ")
            print("`\(*)___________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("" + naam2)
            print("" + str(hp2) + "hp")
            print("                                ")
            print(",                               ")
            print("/-_                             ")
            print("\(*)____________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("" + naam2)
            print("" + str(hp2) + "hp")
            print("                                ")
            print("                                ")
            print("-_                              ")
            print("(*)_____________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("" + naam2)
            print("" + str(hp2) + "hp")
            print("                                ")
            print("                                ")
            print("_                               ")
            print("*)______________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("" + naam2)
            print("" + str(hp2) + "hp")
            print("                                ")
            print("                                ")
            print("                                ")
            print(")_______________________________")
            time.sleep(0.02)
            os.system('cls')
            print("                                ")
            print("  " + naam)
            print("  " + str(hp1) + "hp")
            print("" + naam2)
            print("" + str(hp2) + "hp")
            print("                                ")
            print("                                ")
            print("                                ")
            print("________________________________")
            time.sleep(1)
              
#############################################################################################################################################################
#############################################################################################################################################################
#############################################################################################################################################################
#############################################################################################################################################################

        r1 = random.choice(ratio1)
        r2 = random.choice(ratio2)
        r3 = random.choice(ratio3)
        r4 = random.choice(ratio4)
        r5 = random.choice(ratio5)
        os.system('cls')
        print("                                ")
        print("  " + naam)
        print("  " + str(hp1) + "hp")
        print("                         " + naam2)
        print("                         " + str(hp2) + "hp")
        print("                                ")
        print("    @                      @    ")
        print("   /|\                    /|\   ")
        print("___/ \____________________/ \___")
        
        time.sleep(1)
        print("")
        print("")
        print("")
        print("U bent aan de beurt.")
        time.sleep(1)
        print("")
        print("")
        print("Kies uw wapen:")
        time.sleep(0.5)
        print("")
        print(" 1 Machinegeweer")
        time.sleep(0.2)
        print(" 2 Pistool")
        time.sleep(0.2)
        print(" 3 Granaat")
        time.sleep(0.2)
        print(" 4 Vuurbal")
        time.sleep(0.2)
        print(" 5 Levens")
        time.sleep(0.2)
        print("")
        keuze = input(": ")
        tel = len(keuze)
        if tel == 1:
        
            if keuze == "5":
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("   _@_                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.5)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("    +                           ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("    +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   +                     " + str(hp2) + "hp")
                print("    +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print("    +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print(" +  +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("    +                    " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print(" +  +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("    |                    " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print(" +  +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.05)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("    |                    " + naam2)
                print("   +|+                   " + str(hp2) + "hp")
                print(" +  +  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.05)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("    |                    " + naam2)
                print("   +|+                   " + str(hp2) + "hp")
                print(" +  |  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.05)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   +|+                   " + str(hp2) + "hp")
                print(" +  |  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.05)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print(" +  |  +                        ")
                print("   \@/                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.05)
                for i in range(5):
                    hp1 += int(r5)
                    os.system('cls')
                    print("                                ")
                    print("  " + naam)
                    print("  " + str(hp1) + "hp")
                    print("                         " + naam2)
                    print("   + +                   " + str(hp2) + "hp")
                    print(" +     +                        ")
                    print("   \@/                     @    ")
                    print("    |                     /|\   ")
                    print("___/ \____________________/ \___")          
                    time.sleep(0.1) 
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print(" +                              ")
                print("   _@_                     @    ")
                print("    |                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.3)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   + +                   " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.3)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("   +                     " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.3)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.3)
        
            
            if keuze == "2":
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_                     @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.5)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔                    @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<-                  @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<---                @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<-----              @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<------             @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<--------           @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<----------         @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<------------       @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<--------------     @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<----------------   @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<------------------ @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔<-------------------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔    ----------------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔            --------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_╔                    @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                
                for i in range(5):
                    hp2 -= int(r2)
                    if hp2 < 1:
                        hp2 = 0
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                    @    ")
                        print("   /|                     /|\   ")
                        print("___/ \____________________/ \___")
                        time.sleep(0.1)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                    @    ")
                        print("   /|                     /|\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                    @    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                   *@    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                   *@    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________*?\___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                  ?*@    ")
                        print("   /|                     /#*   ")
                        print("___/ \_____________________?\___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                  ?*@ *  ")
                        print("   /|                     /#*   ")
                        print("___/ \______________________*___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                  ?*@ *  ")
                        print("   /|                     ?#*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                  ?** *  ")
                        print("   /|                      #*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                   ** *  ")
                        print("   /|                      #*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                   ** *  ")
                        print("   /|                       *   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                   *  *  ")
                        print("   /|                           ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_╔                         ")
                        print("   /|                           ")
                        print("___/ \__________________________")
                        time.sleep(3)
                        break
                    os.system('cls')
                    print("                                ")
                    print("  " + naam)
                    print("  " + str(hp1) + "hp")
                    print("                         " + naam2)
                    print("                         " + str(hp2) + "hp")
                    print("                                ")
                    print("    @_╔                    @    ")
                    print("   /|                     /|\   ")
                    print("___/ \____________________/ \___")
                    time.sleep(0.05)
                    os.system('cls')
                    print("                                ")
                    print("  " + naam)
                    print("  " + str(hp1) + "hp")
                    print("                         " + naam2)
                    print("                         ")
                    print("                                ")
                    print("    @_╔                         ")
                    print("   /|                           ")
                    print("___/ \__________________________")
                    time.sleep(0.05)
              
                    
            if keuze == "1":
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @                      @    ")
                print("   /|\                    /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_                     @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.5)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─                 @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(1)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<                @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<-               @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<--              @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<---             @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<----            @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<-----           @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<------          @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<-------         @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<--------        @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<---------       @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<----------      @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<-----------     @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<------------    @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<-------------   @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<--------------  @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─<--------------- @    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─  ---------------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─      -----------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─          -------@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                os.system('cls')
                print("                                ")
                print("  " + naam)
                print("  " + str(hp1) + "hp")
                print("                         " + naam2)
                print("                         " + str(hp2) + "hp")
                print("                                ")
                print("    @_⌐╦═─              ---@    ")
                print("   /|                     /|\   ")
                print("___/ \____________________/ \___")
                time.sleep(0.02)
                               
                for i in range(5):
                    hp2 -= int(r1)
                    if hp2 < 1:
                        hp2 = 0
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                 @    ")
                        print("   /|                     /|\   ")
                        print("___/ \____________________/ \___")
                        time.sleep(0.1)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                 @    ")
                        print("   /|                     /|\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                 @    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                *@    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________* \___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                *@    ")
                        print("   /|                     /#\   ")
                        print("___/ \____________________*?\___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("    @_⌐╦═─               ?*@    ")
                        print("   /|                     /#*   ")
                        print("___/ \_____________________?\___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─               ?*@ *  ")
                        print("   /|                     /#*   ")
                        print("___/ \______________________*___")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─               ?*@ *  ")
                        print("   /|                     ?#*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─               ?** *  ")
                        print("   /|                      #*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                ** *  ")
                        print("   /|                      #*   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                ** *  ")
                        print("   /|                       *   ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                *  *  ")
                        print("   /|                           ")
                        print("___/ \__________________________")
                        time.sleep(0.05)
                        os.system('cls')
                        print("                                ")
                        print("  " + naam)
                        print("  " + str(hp1) + "hp")
                        print("                         " + naam2)
                        print("                         " + str(hp2) + "hp")
                        print("                                ")
                        print("    @_⌐╦═─                      ")
                        print("   /|                           ")
                        print("___/ \__________________________")
                        time.sleep(3)
                        break
                    os.system('cls')
                    print("                                ")
                    print("  " + naam)
                    print("  " + str(hp1) + "hp")
                    print("                         " + naam2)
                    print("                         " + str(hp2) + "hp")
                    print("                                ")
                    print("    @_⌐╦═─                 @    ")
                    print("   /|                     /|\   ")
                    print("___/ \____________________/ \___")
                    time.sleep(0.05)
                    os.system('cls')
                    print("                                ")
                    print("  " + naam)
                    print("  " + str(hp1) + "hp")
                    print("                         " + naam2)
                    print("                         ")
                    print("                                ")
                    print("    @_⌐╦═─                      ")
                    print("   /|                           ")
                    print("___/ \__________________________")
                    time.sleep(0.05)
                    
              
        else:
            time.sleep(0.5)
            print("")
            print("Gelieve EEN nummer in te vullen!")
            time.sleep(2)

        



            
